// GENERATED by greenforge v0.1 — CHARACTERIZATION tests.
// Each assertion pins the CURRENT output of the function. Valid iff current behaviour is the intended spec
// (always true for a pure content-addresser/serializer; REVIEW for business logic). Regenerate if behaviour
// changes intentionally. greenforge confirmed every assertion below kills a real surviving mutant.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import * as M from './doors.mjs';

test('greenforge · nextDecision characterization', () => {
  assert.deepEqual(M["nextDecision"](""), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]("a"), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]("abc"), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]("Zürich"), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]("0"), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]("10"), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]("2"), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](0), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](1), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](-1), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](2), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](10), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](-0.5), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](1.5), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](100), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](0.6180339887), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](true), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](false), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](null), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]([]), {"ok":false,"why":"the queue is empty — the machine is handling everything. Rest."});
  assert.deepEqual(M["nextDecision"]([1,2,3]), {"ok":false,"why":"the queue holds a malformed item"});
  assert.deepEqual(M["nextDecision"]([10,2,1]), {"ok":false,"why":"the queue holds a malformed item"});
  assert.deepEqual(M["nextDecision"]({"a":1}), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]({"a":2}), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]({"n":10}), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"]({"n":2}), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](28), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](27), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](29), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](30), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](1), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](0), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](2), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](-1), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](3), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](-2), {"ok":false,"why":"queue must be a list"});
  assert.deepEqual(M["nextDecision"](4), {"ok":false,"why":"queue must be a list"});
});
