// Generated by build-client.mjs — the offline shell.
const V = 'fallworld-434302c14668';
const SHELL = [".","index.html","manifest.webmanifest","icon.svg"];
self.addEventListener('install', (e) => { self.skipWaiting();
  e.waitUntil(caches.open(V).then(c => c.addAll(SHELL)).catch(() => {})); });
self.addEventListener('activate', (e) => { e.waitUntil(
  caches.keys().then(k => Promise.all(k.filter(x => x !== V).map(x => caches.delete(x)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const u = new URL(e.request.url);
  // Never cache a model provider or the local realm: a stale answer is worse than no answer.
  if (u.hostname === '127.0.0.1' || u.hostname === 'localhost') return;
  if (e.request.method !== 'GET' || u.origin !== location.origin) return;
  e.respondWith(fetch(e.request).then(r => {
    const copy = r.clone(); caches.open(V).then(c => c.put(e.request, copy)).catch(() => {}); return r;
  }).catch(() => caches.match(e.request).then(r => r || caches.match('index.html'))));
});
