// Generated by build-client.mjs — offline shell for the client.
// Versioned by content: a new build means a new cache, so an old page can never be served over a
// new one. Everything the client needs is inlined into index.html, so the shell is the whole app.
const V = 'fallworld-039765874121';
const SHELL = [".","index.html","manifest.webmanifest","icon.svg"];
self.addEventListener('install', (e) => { self.skipWaiting();
  e.waitUntil(caches.open(V).then(c => c.addAll(SHELL)).catch(() => {})); });
self.addEventListener('activate', (e) => { e.waitUntil(
  caches.keys().then(k => Promise.all(k.filter(x => x !== V).map(x => caches.delete(x)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const u = new URL(e.request.url);
  // Never cache the realm: a stale fleet board is the exact lie this client refuses to tell.
  if (u.hostname === '127.0.0.1' || u.hostname === 'localhost') return;
  if (e.request.method !== 'GET' || u.origin !== location.origin) return;
  e.respondWith(fetch(e.request).then(r => {
    const copy = r.clone(); caches.open(V).then(c => c.put(e.request, copy)).catch(() => {}); return r;
  }).catch(() => caches.match(e.request).then(r => r || caches.match('index.html'))));
});
